### ISSUE TITLE
Dogdrip.net

### ISSUE THREAD

**Issue by Magnus111111** [FilteringDev/tinyShield#1]
URL
https://www.dogdrip.net/

FILTERS
tinyShield

Browser
Mozilla Firefox, Google Chrome

Operating System
Microsoft Windows 10

Ad-Blocker
AdGuard for Windows

Userscript Manager
AdGuard for Windows

USERSCRIPT
AdGuard Popup Blocker
Tinyshield

Comment
![캡처](https://github.com/user-attachments/assets/e90d55b5-cf0a-48c4-a595-e76c66d51047)

2024-11-16 dogdrip.net 접속하면 잘못된 애드블록 필터를 사용한다면서 페이지 접근을 막습니다.

**Comment by Magnus111111** [comment]
저기서 시키는 필터 적용한다음 tinyshield 끄고 저 안내창 취소를 누르면 접속이 되긴 합니다

**Comment by piquark6046** [comment]
NextDNS 쓰시나요?

**Comment by piquark6046** [comment]
@gwg02153

**Comment by fli-ck** [comment]
Unable to reproduce.

Browser - Microsoft Edge
Extensions - uBlock Origin, Violentmonkey
Filter - List-KR (uBlock Origin)
Userscript - tinyShield (Violentmonkey)

**Comment by fli-ck** [comment]
@piquark6046 Please check our internal contacts for more details.

**Comment by fli-ck** [comment]
![image](https://github.com/user-attachments/assets/353fbe04-0da6-4699-800b-abf481f83bf7)

**Comment by Magnus111111** [comment]
> @gwg02153

모바일이 아니라 PC입니다.

**Comment by piquark6046** [comment]
AdGuard for Windows 설정 파일을 filters@adguard.com 으로 보내주시겠어요?

**Comment by gwg02153** [comment]
> AdGuard for Windows 설정 파일을 [filters@adguard.com](mailto:filters@adguard.com) 으로 보내주시겠어요?

이젠 또 정상 접속되네요

**Comment by Magnus111111** [comment]
뭔지 모르겠는데 tinyShield 켜고 적용하라던 필터 삭제하고 재접속해도 들어가지고 광고도 안나오지만 tinyShield 켜진상태에선 내가 쓴 게시물 또는 댓글에 댓글이 달리면 아래 이미지에 빨간색 숫자가 적히면서 알림창이 떠야되는데 안뜨고 그냥 회원 프로필 수정창으로 넘어가지네요
![캡처2](https://github.com/user-attachments/assets/9649aad9-befd-46bc-888a-814c8fa863d5)

**Comment by d3vdev** [comment]
AdGuard 팝업 차단기 스크립트를 켜면 저도 동일한 오류가 나오네요 
해당 스크립트와 충돌이 있는것 같습니다.

**Comment by piquark6046** [comment]
https://github.com/List-KR/tinyShield/issues/1#issuecomment-2480564371
@gwg02153 
아래 규칙을 테스트해보시겠어요?


```adblock
@@||dogdrip.net^$extension="AdGuard Popup Blocker"
```

**Comment by Magnus111111** [comment]
> [#1 (comment)](https://github.com/List-KR/tinyShield/issues/1#issuecomment-2480564371) @gwg02153 아래 규칙을 테스트해보시겠어요?
> 
> ```
> @@||dogdrip.net^$extension="AdGuard Popup Blocker"
> ```

작동하는것 같습니다
