### ISSUE TITLE
inven 오류

### ISSUE THREAD

**Issue by rsh6929** [FilteringDev/tinyShield#3]
![Screenshot_20241213_004330_Samsung Internet](https://github.com/user-attachments/assets/467499c8-94a4-4c31-9093-521fcc4b4c9d)
![Screenshot_20241213_010335_Samsung Internet](https://github.com/user-attachments/assets/f62f2f5c-d4e0-4a11-b467-2015b1cb24e8)

microshield를 삭제해도 adguard를 종료해도 새로고침을 하면 팝업이 다시 생깁니다

**Comment by rsh6929** [comment]
이 게시글을 올리고 바로 문제가 사라졌습니다...

**Comment by piquark6046** [comment]
그럼 이슈를 닫아도 되나요?

**Comment by rsh6929** [comment]
네
